# Generated by Django 4.1.1 on 2023-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200)),
                ('amount_in_word_naira', models.CharField(max_length=200)),
                ('amount_in_word_kobo', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('amount_in_digit_naira', models.CharField(max_length=200)),
                ('amount_in_digit_kobo', models.CharField(max_length=200)),
            ],
        ),
    ]
