# Generated by Django 4.1.1 on 2023-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('signature', models.FileField(upload_to='signature')),
            ],
        ),
    ]
