# Generated by Django 4.1.1 on 2023-03-16 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_rename_transaction2_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 8, 9, 10, 372938)),
        ),
    ]
