# Generated by Django 4.1.1 on 2023-03-16 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0010_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 18, 30, 57, 937121)),
        ),
    ]
