# Generated by Django 4.1.1 on 2023-03-16 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0016_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200)),
                ('amount_in_word_naira', models.CharField(max_length=200)),
                ('amount_in_word_kobo', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('amount_in_digit_naira', models.CharField(max_length=200)),
                ('amount_in_digit_kobo', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 19, 39, 21, 654976)),
        ),
    ]
