# Generated by Django 4.1.1 on 2023-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0017_transaction2_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterField(
            model_name='transaction2',
            name='date',
            field=models.DateField(),
        ),
    ]
