# Generated by Django 4.1.1 on 2023-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0018_logo_delete_transaction_alter_transaction2_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration2',
            name='businesslogo',
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(upload_to='businesslogo'),
        ),
    ]
