# Generated by Django 4.1.1 on 2023-04-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0019_remove_userregistration2_businesslogo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signature',
        ),
    ]
