# Generated by Django 4.1.1 on 2023-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0021_userregistration2_businessaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
    ]
