# Generated by Django 4.1.1 on 2023-05-10 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0023_key_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='datey',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
