# Generated by Django 4.1.1 on 2023-12-10 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0025_alter_logo_datey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='datey',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
        migrations.CreateModel(
            name='tmp_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('businessname', models.CharField(max_length=200)),
                ('businessaddress', models.CharField(default='Your Address Here', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
