# Generated by Django 4.1.1 on 2023-05-11 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0027_tmpreg_delete_tmp_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration2',
            name='email',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AlterField(
            model_name='logo',
            name='datey',
            field=models.DateField(default=datetime.date(2023, 6, 10)),
        ),
    ]
