# Generated by Django 4.1.1 on 2023-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0028_userregistration2_email_alter_logo_datey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmpforgetpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
