# Generated by Django 4.1.1 on 2023-05-13 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0031_tmpforgetpassword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration2',
            name='receipt_type',
            field=models.CharField(default='receipt1', max_length=200),
        ),
        migrations.AlterField(
            model_name='logo',
            name='datey',
            field=models.DateField(default=datetime.date(2023, 6, 12)),
        ),
    ]
